// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcM8Y1KCmQ2xTmHgN2XJ7XqiBUmKvZTcY',
    appId: '1:344544208508:web:d6eba245766b2057ce0bf9',
    messagingSenderId: '344544208508',
    projectId: 'weather-54c9e',
    authDomain: 'weather-54c9e.firebaseapp.com',
    databaseURL: 'https://weather-54c9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-54c9e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwmB_dLhj6TfcP8-q48Pw5et1V6QWdge4',
    appId: '1:344544208508:android:9ae633023255adcace0bf9',
    messagingSenderId: '344544208508',
    projectId: 'weather-54c9e',
    databaseURL: 'https://weather-54c9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-54c9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy3YNfIoNFYCCmHKZKmBR6zWX7879soZI',
    appId: '1:344544208508:ios:517ce0a8f15a12f9ce0bf9',
    messagingSenderId: '344544208508',
    projectId: 'weather-54c9e',
    databaseURL: 'https://weather-54c9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-54c9e.firebasestorage.app',
    iosBundleId: 'com.example.weatherstation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy3YNfIoNFYCCmHKZKmBR6zWX7879soZI',
    appId: '1:344544208508:ios:517ce0a8f15a12f9ce0bf9',
    messagingSenderId: '344544208508',
    projectId: 'weather-54c9e',
    databaseURL: 'https://weather-54c9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-54c9e.firebasestorage.app',
    iosBundleId: 'com.example.weatherstation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcM8Y1KCmQ2xTmHgN2XJ7XqiBUmKvZTcY',
    appId: '1:344544208508:web:546ed5bda48abaf0ce0bf9',
    messagingSenderId: '344544208508',
    projectId: 'weather-54c9e',
    authDomain: 'weather-54c9e.firebaseapp.com',
    databaseURL: 'https://weather-54c9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-54c9e.firebasestorage.app',
  );

}